### ISSUE TITLE
What Node version to support?

### ISSUE THREAD

**Issue by addisonElliott** [mongodb-js/mongodb-topology-manager#12]
This is more of a discussion to see what **minimum** version of Node this library should support. It is briefly mentioned by @mbroadst in #9 that this library should be "modernized". 

In my PR #11, I had to bump the minimum Node version to 6 because of the prebuild-install library used by kerberos requires that. 

Should the library switch to Node 8 so that async/await can be used?

**Comment by mbroadst** [comment]
Hey @addisonElliott, I'm going to close this because we've been addressing it as part of your pull request.
