### ISSUE TITLE
Cannot read property 'toString' of null, mongodb-topology-manager/lib/replset.js:124             .toString()

### ISSUE THREAD

**Issue by mmc509** [mongodb-js/mongodb-topology-manager#24]
got this error:

```
/Users/michelle/Downloads/MEAN/back-end/node_modules/mongodb-topology-manager/lib/replset.js:124
            .toString()
             ^

TypeError: Cannot read property 'toString' of null
    at ChildProcess.<anonymous> (/Users/michelle/Downloads/MEAN/back-end/node_modules/mongodb-topology-manager/lib/replset.js:124:14)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Socket.stream.socket.on (internal/child_process.js:381:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:610:12)
```

but I have checked my versions are:
    "mongodb-topology-manager": "^2.1.0",
    "mongoose": "^5.4.1"

what's wrong?

**Comment by mbroadst** [comment]
Hi @mmc509, this seems to be some particularly brittle code in the topology manager's code for process close handling. Would you mind printing out the contents of `stdout` on [this line](https://github.com/mongodb-js/mongodb-topology-manager/blob/v2.1.0/lib/replset.js#L116) for me? I suspect that there is an issue with binary paths here, and that `mongod` isn't actually being run at all.

**Comment by Ladinn** [comment]
@mbroadst Also having this issue. Line 117 of ```replset.js``` debug got the following:

```
stdout = ""
versionMatch = undefined
```

**Comment by Ladinn** [comment]
After looking further, it looks like ```mongod --version``` is being run in a child process. However, I don't have mongod installed as I didn't realize that running a replica set required it to be installed on the client machine.

It looks like simply installing mongo should resolve this issue. (Maybe update the readme for those not as well versed with Mongo?)

**Comment by mbroadst** [comment]
@Ladinn I reopened [this ticket](https://jira.mongodb.org/browse/NODE-1676) in our JIRA to resolve this very issue. Thanks for bringing it to our attention again.

**Comment by xyzzyxyzzy0077** [comment]
Hi, I'm having the exact error. Is this issue fixed?

**Comment by zacharytyhacz** [comment]
hello guys @mbroadst @mmc509  I am getting this same issue.

I think my issue is somewhat unique, since I am on Linux and I have mongodb in a docker container.

I am just setting up basic replica set stuff like this:
```javascript
import { ReplSet } from 'mongodb-topology-manager';
import mongoose from "mongoose";

const setupReplicaSet = async () => { 
    const replSet = new ReplSet('mongod', [
        { options: { port: 31000, dbpath: `${__dirname}/data/db/31000`, bind_ip: 'localhost' } },
        { options: { port: 31001, dbpath: `${__dirname}/data/db/31001`, bind_ip: 'localhost' } },
        { options: { port: 31002, dbpath: `${__dirname}/data/db/31002`, bind_ip: 'localhost' } }
    ], { replSet: 'rs0' });

    try {
        await replSet.purge();
        await replSet.start();

        console.log('Replica set started...');
    } catch (err) {
        console.error("Failed to start replica sets:", err);
    }
}

export default async () => {
    await setupReplicaSet();

    const uri = `mongodb://localhost:31000,localhost:31001,localhost:31002/test?replicaSet=rs0`;

    await mongoose.connect(uri);
}
```

Then on running this, I get the same error mentioned in this issue:
```bash
/home/zac/Projects/hugo/app/application/server/node_modules/mongodb-topology-manager/lib/replset.js:124
            .toString()
             ^

TypeError: Cannot read property 'toString' of null
    at ChildProcess.<anonymous> (/home/zac/Projects/hugo/app/application/server/node_modules/mongodb-topology-manager/lib/replset.js:124:14)
    at ChildProcess.emit (node:events:376:20)
    at maybeClose (node:internal/child_process:1063:16)
    at Socket.<anonymous> (node:internal/child_process:449:11)
    at Socket.emit (node:events:376:20)
    at Pipe.<anonymous> (node:net:666:12)
```

my versions:
```json
"mongodb-topology-manager": "^2.1.0",
"mongoose": "^5.9.19",
```

Any ideas how to work around at least? I can see that Jira ticket is still open


EDIT: 

I did more searching, turns out you need to have `mongod` command accessible, because I had mongo in a docker container and not installed on my host os,`mongod` was not a valid command.

So I fully installed the mongo binaries that includes the standard `mongod` command, and now it is working, however it is hanging/stuck at this point in my code above:

```javascript
...
await replSet.start();
...
```

related: https://stackoverflow.com/questions/59054957/is-there-a-way-to-create-a-replset-using-mongo-topology-manager

**Comment by emadum** [comment]
Hi @zacharytyhacz, we don't officially support this library because we are no longer using it internally. However we'd welcome a PR for this fix!

**Comment by zacharytyhacz** [comment]
@emadum hello, thanks for letting me know. I just created a totally different way on doing what I was trying to do without using `.watch()` and going through all of this.
