### ISSUE TITLE
Error: failed to start mongod

### ISSUE THREAD

**Issue by SamuelEarl** [mongodb-js/mongodb-topology-manager#5]
I am creating an app with hapi.js and MongoDB change streams. I followed this tutorial to figure out how to setup replica sets to get change streams to work: http://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-change-streams.html. I am using the Mongoose driver and there is a heading toward the bottom of the tutorial titled "Change Streams in Mongoose" that explains how to configure Mongoose to use change streams.

The problem that I am having is that I get this error in the terminal when I start my app:
```
Error: failed to start mongod with options --bind_ip=localhost,--port=31000,--dbpath=/path/to/mongodb-repl-sets/31000,--replSet=nrd-mongo-repl
```
I have my app configured with Nodemon, so if I save a server-side file, then Nodemon will trigger a reload and the error goes away and the database seems to work without any problems. However, the error will display at random times after I save a server-side file.

This is the part of my `server.js` file that sets up the replica set and connects to MongoDB through Mongoose:

```
// -----------------------------------------------------
// Configure the MongoDB replica set for change streams
// -----------------------------------------------------
await console.log(createTimestamp(), `"Starting replica set..."`);

// Start a 3-node replica set on ports 31000, 31001, 31002. 
// The name of this replica set is "nrd-mongo-repl".
const replSet = new ReplSet('mongod', [
  { options: { bind_ip: 'localhost', port: 31000, dbpath: `${__dirname}/mongodb-repl-sets/31000` } },
  { options: { bind_ip: 'localhost', port: 31001, dbpath: `${__dirname}/mongodb-repl-sets/31001` } },
  { options: { bind_ip: 'localhost', port: 31002, dbpath: `${__dirname}/mongodb-repl-sets/31002` } }
], { replSet: 'nrd-mongo-repl' } );

// Initialize the replica set
await replSet.purge();
await replSet.start();
await console.log(createTimestamp(), `"Replica set is running"`);
    
// ------------------------------------------------------
// Connect to MongoDB server through the Mongoose driver
// ------------------------------------------------------
const replSetUri = 'mongodb://localhost:31000,localhost:31001,localhost:31002/nrd?replicaSet=nrd-mongo-repl';

// Once the hapi server is started, connect to MongoDB server through Mongoose using a 
// JavaScript await function. The {} is an empty options object, which is an optional argument.
const dbConnection = await Mongoose.connect(replSetUri, {});

// Create at least one of your collections here to avoid this error "MongoError: cannot 
// open $changeStream for non-existent database: <db_name>"
await Mongoose.connection.createCollection('discharge_time');
```

Does anyone have any thoughts on what is going on?

Thank you for your help!

**Comment by jcotero** [comment]
I'm also using the same source code. My problem is that (it seems) the database is being restarted... I lose all my collections every time I run the server.

I also have an open question at Stackoverflow: https://stackoverflow.com/questions/49540337/node-js-mongodb-mongodb-topology-manager-why-im-i-losing-my-collections

I came here expecting to understand those purge and start commands, but the readme didn't help much. Any tips on what's going on?

**Comment by daprahamian** [comment]
Hi @SamuelEarl and @jcotero,

What this script is doing is destroying a recreating a ReplicaSet every time that the script is run. That is what the `purge` and `start` do. @jcotero, that is why whenever you run the script, you are losing all of your data. Similarly, if you run this script too many times in close proximity, you may attempt to delete and/or create a replicaset two times in a row, which may lead to the error that @SamuelEarl is seeing.

If you are attempting to do more than try out changestreams, and want to use them in a production environment, I would not use `mongodb-topology-manager`, but would instead follow [our tutorials for deploying a replica set](https://docs.mongodb.com/manual/administration/replica-set-deployment/).

Let me know if you have further questions.

**Comment by midthun** [comment]
I am having a similar issue, this seemed like an easy way to set up a replica set locally for testing and development. However, I would love to keep my data when I run my script to start the replica set again. Is there such a feature here that I am not aware of? If I try to just start it again with `start()` or `restart()`, I get the `MongoError: already initialized` error (not doing this in close proximity).

**Comment by daprahamian** [comment]
@midthun AFAIK there isn't currently a way to do that. If you'd like the feature, you can request it on [our JIRA](https://jira.mongodb.org/).

**Comment by mbroadst** [comment]
Closing this for now, please file JIRAs for any further questions. Thanks!

**Comment by kavuri** [comment]
> @daprahamian Ok I see, no problem, it is just a nice to have feature. For now I can work around it with a few modifications. If I set [this](https://github.com/mongodb-js/mongodb-topology-manager/blob/master/lib/replset.js#L188) to `true`, I can restart the replica set with the `start()` function so it does not purge the data. However, I do not know the side effects of this.

@midthun I hit on the same problem and would want to retain data after every restart. The 'this' you mentioned at line 188 is no more there (blank now). Can you please let me know what that line refers to? Thanks

**Comment by kavuri** [comment]
Ignore my question. There is an option "restart" that does the job of starting the replica set without purge
